# contians all dependencies and versions for creating a reproducible Conda environment.

name: movierecs
channels: [conda-forge]
dependencies:
  - python=3.11
  - pip
  - pip:
      - numpy
      - pandas
      - scipy
      - scikit-learn
      - fastapi
      - uvicorn[standard]
      - joblib